"""update coach profile table

Revision ID: 095cfce076eb
Revises: 1c4c00cdfaad
Create Date: 2026-10-08 16:05:16.391464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '095cfce076eb'
down_revision: Union[str, Sequence[str], None] = '1c4c00cdfaad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coach_profiles', 'profile_photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach_profiles', sa.Column('profile_photo', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
