"""add video_duration and video_display_duration to coach_profiles

Revision ID: 1c4c00cdfaad
Revises: c66ba7b0b27e
Create Date: 2026-10-08 15:16:01.753713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c4c00cdfaad'
down_revision: Union[str, Sequence[str], None] = 'c66ba7b0b27e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach_profiles', sa.Column('video_duration', sa.Integer(), nullable=True))
    op.add_column('coach_profiles', sa.Column('video_display_duration', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coach_profiles', 'video_display_duration')
    op.drop_column('coach_profiles', 'video_duration')
    # ### end Alembic commands ###
