"""create_coach_availabilities_table

Revision ID: 3216cdc27e26
Revises: 364771b5eb09
Create Date: 2026-10-10 14:52:44.569796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3216cdc27e26'
down_revision: Union[str, Sequence[str], None] = '364771b5eb09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_availabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coach_profile_id', sa.Integer(), nullable=False),
    sa.Column('weekly', sa.JSON(), nullable=False),
    sa.Column('on_call', sa.JSON(), nullable=False),
    sa.Column('on_call_enabled', sa.Boolean(), nullable=False),
    sa.Column('time_off', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coach_profile_id'], ['coach_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_availabilities_coach_profile_id'), 'coach_availabilities', ['coach_profile_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coach_availabilities_coach_profile_id'), table_name='coach_availabilities')
    op.drop_table('coach_availabilities')
    # ### end Alembic commands ###
