"""update otp tables

Revision ID: 5150bbd20c90
Revises: 4fca3ff74c2b
Create Date: 2026-10-03 12:23:40.071916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5150bbd20c90'
down_revision: Union[str, Sequence[str], None] = '4fca3ff74c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_verifications', sa.Column('otp_code', sa.String(length=6), nullable=False))
    op.drop_column('otp_verifications', 'otp')
    op.drop_column('otp_verifications', 'verified_at')
    op.drop_column('otp_verifications', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_verifications', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('otp_verifications', sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('otp_verifications', sa.Column('otp', sa.VARCHAR(length=6), autoincrement=False, nullable=False))
    op.drop_column('otp_verifications', 'otp_code')
    # ### end Alembic commands ###
