"""create_coach_reviews_table

Revision ID: 7bea0e0f4562
Revises: 3216cdc27e26
Create Date: 2026-10-10 15:53:37.603396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bea0e0f4562'
down_revision: Union[str, Sequence[str], None] = '3216cdc27e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coach_profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coach_profile_id'], ['coach_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_reviews_coach_profile_id'), 'coach_reviews', ['coach_profile_id'], unique=False)
    op.create_index(op.f('ix_coach_reviews_user_id'), 'coach_reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coach_reviews_user_id'), table_name='coach_reviews')
    op.drop_index(op.f('ix_coach_reviews_coach_profile_id'), table_name='coach_reviews')
    op.drop_table('coach_reviews')
    # ### end Alembic commands ###
