"""update otp verification table

Revision ID: aa177982dddd
Revises: ab5b5e87d6ad
Create Date: 2026-10-03 16:29:43.928839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa177982dddd'
down_revision: Union[str, Sequence[str], None] = 'ab5b5e87d6ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_verifications_user_id'), table_name='otp_verifications')
    op.create_unique_constraint(None, 'otp_verifications', ['user_id'])
    op.drop_column('otp_verifications', 'purpose')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_verifications', sa.Column('purpose', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'otp_verifications', type_='unique')
    op.create_index(op.f('ix_otp_verifications_user_id'), 'otp_verifications', ['user_id'], unique=False)
    # ### end Alembic commands ###
