"""update otp verification table

Revision ID: ab5b5e87d6ad
Revises: 6e7754e63c58
Create Date: 2026-10-03 15:52:36.399522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab5b5e87d6ad'
down_revision: Union[str, Sequence[str], None] = '6e7754e63c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_verifications', sa.Column('purpose', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_verifications', 'purpose')
    # ### end Alembic commands ###
