"""create_provider_coach_profile_and_category_tables

Revision ID: c66ba7b0b27e
Revises: eaebcc38a22e
Create Date: 2026-10-07 16:12:07.984440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c66ba7b0b27e'
down_revision: Union[str, Sequence[str], None] = 'eaebcc38a22e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('coach_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_photo', sa.String(length=500), nullable=True),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('introduction_video', sa.String(length=500), nullable=True),
    sa.Column('introduction_video_duration', sa.Integer(), nullable=True),
    sa.Column('introduction_video_thumbnail', sa.String(length=500), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('affiliate_commission_percent', sa.String(length=20), nullable=False),
    sa.Column('auto_approve_affiliates', sa.Boolean(), nullable=False),
    sa.Column('expertises', sa.JSON(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('completed_sessions_count', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_profiles_user_id'), 'coach_profiles', ['user_id'], unique=True)
    op.create_table('coach_certifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coach_profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('document', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coach_profile_id'], ['coach_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_certifications_coach_profile_id'), 'coach_certifications', ['coach_profile_id'], unique=False)
    op.create_table('coach_profile_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coach_profile_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_profile_id'], ['coach_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_profile_categories_category_id'), 'coach_profile_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_coach_profile_categories_coach_profile_id'), 'coach_profile_categories', ['coach_profile_id'], unique=False)
    op.create_table('coach_qualifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coach_profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('document', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coach_profile_id'], ['coach_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_qualifications_coach_profile_id'), 'coach_qualifications', ['coach_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coach_qualifications_coach_profile_id'), table_name='coach_qualifications')
    op.drop_table('coach_qualifications')
    op.drop_index(op.f('ix_coach_profile_categories_coach_profile_id'), table_name='coach_profile_categories')
    op.drop_index(op.f('ix_coach_profile_categories_category_id'), table_name='coach_profile_categories')
    op.drop_table('coach_profile_categories')
    op.drop_index(op.f('ix_coach_certifications_coach_profile_id'), table_name='coach_certifications')
    op.drop_table('coach_certifications')
    op.drop_index(op.f('ix_coach_profiles_user_id'), table_name='coach_profiles')
    op.drop_table('coach_profiles')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
